// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Dorsal",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Dorsal",
            targets: ["AppModule"],
            bundleIdentifier: "cpp.Dorsalv1",
            teamIdentifier: "879HFN9R93",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "We need your microphone to record dreams"),
                .speechRecognition(purposeString: "We need speech recognition to transcribe dreams"),
                .photoLibrary(purposeString: "We need your photo library to upload your photo.")
            ],
            appCategory: .healthcareFitness
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)