// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Dorsal",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Dorsal",
            targets: ["AppModule"],
            bundleIdentifier: "cpp.Dorsal",
            teamIdentifier: "879HFN9R93",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight(.when(deviceFamilies: [.pad])),
                .landscapeLeft(.when(deviceFamilies: [.pad])),
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "We need your microphone to record dreams"),
                .photoLibrary(purposeString: "We need your photo library to upload your photo."),
                .contacts(purposeString: "We need your contacts to link people.")
            ],
            appCategory: .healthcareFitness
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("VocalFatigueModel.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)